stages:
  - test
  - publish

test-debug-sdk-lo:
  image: node:6.9.1
  stage: test
  script:
    - cd cl-sdk-js-lo
    - curl -u$ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD https://edify.jfrog.io/edify/api/npm/auth > ~/.npmrc
    - echo registry=http://edify.jfrog.io/edify/api/npm/npm-edify >> ~/.npmrc
    - npm install
    # - npm test
    # Currently there are only integration tests that won't be executed.

release-sdk-lo:
  image: node:6.9.1
  stage: publish
  only:
    - master
  script:
    - cd cl-sdk-js-lo
    - curl -u$ARTIFACTORY_USERNAME:$ARTIFACTORY_PASSWORD https://edify.jfrog.io/edify/api/npm/auth > ~/.npmrc
    - echo registry=http://edify.jfrog.io/edify/api/npm/npm-edify >> ~/.npmrc
    - npm install
    - npm publish
